.PATH:${.CURDIR}/../../lib

PROG = pathset_test
SRCS = error.c sha1.c pathset.c pathset_test.c

CPPFLAGS = -I${.CURDIR}/../../include -I${.CURDIR}/../../lib
LDADD = 

NOMAN = yes

.include <bsd.regress.mk>
