.\"
.\" Copyright (c) 2017 Martin Pieuchot
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOT 1
.Os
.Sh NAME
.Nm got
.Nd distributed version control system
.Sh SYNOPSIS
.Nm
.Ar command
.Op Fl h
.Op Ar arg ...
.Sh DESCRIPTION
.Nm
is a distributed version control system which prioritizes ease of use
and simplicity over flexibility.
.Pp
.Nm
stores the history of files tracked in version control in a repository
which happens to use the same on-disk format as the so-called
.Dq bare
repositories created by the popular Git version control system.
This repository format is described in
.Xr got-repository 5 .
.Pp
.Nm
is a
.Dq distributed
version control system because every copy of a repository is writeable.
Modifications made to files can be synchronized between repositories
automatically at any time.
.Pp
Files managed by
.Nm
must be checked out from the repository for modification.
Checked out files are stored in a
.Em work tree
which is placed at an arbitrary directory in the filesystem hierarchy.
The format of a
.Nm
work tree is described in
.Xr got-worktree 5 .
.Pp
.Nm
provides global and command-specific options.
Global options must preceed the command name, and are as follows:
.Bl -tag -width tenletters
.It Fl h
Display usage information.
.El
.Pp
The commands are as follows:
.Bl -tag -width checkout
.It Cm checkout
Copy files from a repository into a new work tree.
The work tree may be restricted to a subset of the repository's tree
hierarchy by specifying the
.Fl p Ar prefix
option.
In this case, only files beneath the specified directory prefix will
be checked out.
.\".It Cm status
.\"Show current status of files.
.It Cm log
Display history of the repository.
.El
.Sh EXIT STATUS
.Ex -std got
.Sh SEE ALSO
.Xr got-repository 5
.Xr got-worktree 5
