.\"
.\" Copyright (c) 2022 Stefan Sperling
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOTCTL 8
.Os
.Sh NAME
.Nm gotctl
.Nd control the Game of Trees Daemon
.Sh SYNOPSIS
.Nm
.Op Fl hV
.Op Fl f Ar path
.Ar command
.Op Ar arg ...
.Sh DESCRIPTION
.Nm
controls the
.Xr gotd 8
daemon.
.Pp
The options for
.Nm
are as follows:
.Bl -tag -width Ds
.It Fl h
Display usage information and exit immediately.
.It Fl f Ar path
Set the
.Ar path
to the unix socket which
.Xr gotd 8
is listening on.
If not specified, the default path
.Pa /var/run/gotd.sock
will be used.
.It Fl V , -version
Display program version and exit immediately.
.El
.Pp
The commands for
.Nm
are as follows:
.Bl -tag -width Ds
.It Cm info
Display information about a running
.Xr gotd 8
instance.
This operation requires root privileges.
.It Cm stop
Stop a running
.Xr gotd 8
instance.
This operation requires root privileges.
.El
.Sh SEE ALSO
.Xr got 1 ,
.Xr gotd 8
.Sh AUTHORS
.An Stefan Sperling Aq Mt stsp@openbsd.org
