.\"
.\" Copyright (c) 2018 Stefan Sperling
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt TOG 1
.Os
.Sh NAME
.Nm tog
.Nd Git repository browser
.Sh SYNOPSIS
.Nm
.Op Ar command
.Op Fl h
.Op Ar arg ...
.Pp
.Nm
.Ar path
.Sh DESCRIPTION
.Nm
is an interactive read-only browser for Git repositories.
This repository format is described in
.Xr git-repository 5 .
.Pp
.Nm
supports several types of views which display repository data:
.Bl -tag -width Ds
.It Log view
Displays commits in the repository's history.
This view is displayed initially if no
.Ar command
is specified, or if just a
.Ar path
is specified.
.It Diff view
Displays changes made in a particular commit.
.It Blame view
Displays the line-by-line history of a file.
.It Tree view
Displays the tree corresponding to a particular commit.
.It Ref view
Displays references in the repository.
.El
.Pp
.Nm
provides global and command-specific key bindings and options.
Some command-specific key bindings may be prefixed with an integer, which is
denoted by N in the descriptions below, and is used as a modifier to the
operation as indicated.
.Nm
will echo digits to the screen when count modifiers are entered, and complete
the sequence upon input of the first non-numeric character.
Count modifiers can be aborted by entering an unmapped key.
Once a compound command is executed, the operation can be cancelled with
.Cm C-g
or
.Cm Backspace .
The global key bindings are:
.Bl -tag -width Ds
.It Cm Q
Quit
.Nm .
.It Cm q
Quit the view which is in focus.
.It Cm Tab
Switch focus between views.
.It Cm F
Toggle fullscreen mode for a split-screen view.
.Nm
will automatically use split-screen views if the size of the terminal
window is sufficiently large.
.It Cm S
Switch the current split-screen layout, and render all active views in
this new layout.
If the terminal is not wide enough when switching to a vertical split,
views will render in fullscreen.
.It Cm -
When in a split-screen view, decrease the size of the focussed split
N increments (default: 1).
.It Cm +
When in a split-screen view, increase the size of the focussed split
N increments (default: 1).
.El
.Pp
Global options must precede the command name, and are as follows:
.Bl -tag -width tenletters
.It Fl h
Display usage information.
.It Fl V , -version
Display program version and exit immediately.
.El
.Pp
The commands for
.Nm
are as follows:
.Bl -tag -width blame
.It Cm log Oo Fl b Oc Oo Fl c Ar commit Oc Oo Fl r Ar repository-path Oc Op Ar path
Display history of a repository.
If a
.Ar path
is specified, show only commits which modified this path.
If invoked in a work tree, the
.Ar path
is interpreted relative to the current working directory,
and the work tree's path prefix is implicitly prepended.
Otherwise, the path is interpreted relative to the repository root.
.Pp
This command is also executed if no explicit command is specified.
.Pp
The key bindings for
.Cm tog log
are as follows (N denotes optional prefixed count modifier):
.Bl -tag -width Ds
.It Cm Down-arrow, j, >, Full stop, Ctrl-n
Move the selection cursor down N lines (default: 1).
.It Cm Up-arrow, k, <, Comma, Ctrl-p
Move the selection cursor up N lines (default: 1).
.It Cm Right-arrow, l
Scroll log message field to the right N increments (default: 1).
.br
Log message moves left on the screen.
.It Cm Left-arrow, h
Scroll log message field to the left N increments (default: 1).
.br
Log message moves right on the screen.
.It Cm $
Scroll log message field to the rightmost position.
.It Cm 0
Scroll log message field to the leftmost position.
.It Cm Page-down, Space, Ctrl+f, f
Move the selection cursor down N pages (default: 1).
.It Cm Page-up, Ctrl+b, b
Move the selection cursor up N pages (default: 1).
.It Cm Ctrl+d, d
Move the selection cursor down N half pages (default: 1).
.It Cm Ctrl+u, u
Move the selection cursor up N half pages (default: 1).
.It Cm Home, g
Move the cursor to the newest commit.
.It Cm End, G
Move the cursor to the oldest commit.
This will traverse all commits on the current branch which may take
a long time depending on the number of commits in branch history.
If needed, this operation can be cancelled with
.Cm C-g
or
.Cm Backspace .
.It Cm Enter
Open a
.Cm diff
view showing file changes made in the currently selected commit.
.It Cm t
Open a
.Cm tree
view showing the tree for the currently selected commit.
.It Cm Backspace
Show log entries for the parent directory of the currently selected path.
However when an active search is in progress or when additional commits
are loaded,
.Cm Backspace
aborts the running operation.
.It Cm /
Prompt for a search pattern and start searching for matching commits.
The search pattern is an extended regular expression which is matched
against a commit's author name, committer name, log message, and
commit ID SHA1 hash.
Regular expression syntax is documented in
.Xr re_format 7 .
.It Cm n
Find the Nth next commit which matches the current search pattern (default: 1).
.br
Searching continues until either a match is found or
.Cm C-g
or the
.Cm Backspace
key is pressed.
.It Cm N
Find the Nth previous commit which matches the current search pattern
(default: 1).
.br
Searching continues until either a match is found or
.Cm C-g
or the
.Cm Backspace
key is pressed.
.It Cm Ctrl+l
Reload the
.Cm log
view with new commits found in the repository.
.It Cm B
Reload the
.Cm log
view and toggle display of merged commits.
The
.Fl b
option determines whether merged commits are displayed initially.
.It Cm r
Open a
.Cm ref
view listing all references in the repository.
This can then be used to open a new
.Cm log
view for arbitrary branches and tags.
.El
.Pp
The options for
.Cm tog log
are as follows:
.Bl -tag -width Ds
.It Fl b
Display individual commits which were merged into the current branch
from other branches.
By default,
.Cm tog log
shows the linear history of the current branch only.
The
.Cm B
key binding can be used to toggle display of merged commits at run-time.
.It Fl c Ar commit
Start traversing history at the specified
.Ar commit .
The expected argument is the name of a branch or a commit ID SHA1 hash.
An abbreviated hash argument will be expanded to a full SHA1 hash
automatically, provided the abbreviation is unique.
If this option is not specified, default to the work tree's current branch
if invoked in a work tree, or to the repository's HEAD reference.
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
If this directory is a
.Xr got 1
work tree, use the repository path associated with this work tree.
.El
.It Cm diff Oo Fl a Oc Oo Fl C Ar number Oc Oo Fl r Ar repository-path Oc Oo Fl w Oc Ar object1 Ar object2
Display the differences between two objects in the repository.
Treat each of the two arguments as a reference, a tag name, or an object
ID SHA1 hash, and display differences between the corresponding objects.
Both objects must be of the same type (blobs, trees, or commits).
An abbreviated hash argument will be expanded to a full SHA1 hash
automatically, provided the abbreviation is unique.
.Pp
The key bindings for
.Cm tog diff
are as follows (N denotes optional prefixed count modifier):
.Bl -tag -width Ds
.It Cm a
Toggle treatment of file contents as ASCII text even if binary data was
detected.
.It Cm Down-arrow, j, Ctrl-n
Scroll down N lines (default: 1).
.It Cm Up-arrow, k, Ctrl-p
Scroll up N lines (default: 1).
.It Cm Right-arrow, l
Scroll view to the right N increments (default: 1).
.br
Diff output moves left on the screen.
.It Cm Left-arrow, h
Scroll view to the left N increments (default: 1).
.br
Diff output moves right on the screen.
.It Cm $
Scroll view to the rightmost position.
.It Cm 0
Scroll view left to the start of the line.
.It Cm Page-down, Space, Ctrl+f, f
Scroll down N pages (default: 1).
.It Cm Page-up, Ctrl+b, b
Scroll up N pages (default: 1).
.It Cm Ctrl+d, d
Scroll down N half pages (default: 1).
.It Cm Ctrl+u, u
Scroll up N half pages (default: 1).
.It Cm Home, g
Scroll to the top of the view.
.It Cm End, G
Scroll to the bottom of the view.
.It Cm \&[
Reduce diff context by N lines (default: 1).
.It Cm \&]
Increase diff context by N lines (default: 1).
.It Cm <, Comma
If the
.Cm diff
view was opened via the
.Cm log
view, move to the Nth previous (younger) commit.
If the diff was opened via the
.Cm blame
view, move to the Nth previous line and load the corresponding commit
(default: 1).
.It Cm >, Full stop
If the
.Cm diff
view was opened via the
.Cm log
view, move to the Nth next (older) commit.
If the diff was opened via the
.Cm blame
view, move to the Nth next line and load the corresponding commit (default: 1).
.It Cm /
Prompt for a search pattern and start searching for matching lines.
The search pattern is an extended regular expression.
Regular expression syntax is documented in
.Xr re_format 7 .
.It Cm n
Find the Nth next line which matches the current search pattern (default: 1).
.It Cm N
Find the Nth previous line which matches the current search pattern
(default: 1).
.It Cm w
Toggle display of whitespace-only changes.
.It Cm A
Change the diff algorithm.
Supported diff algorithms are Myers (quick and dirty) and
Patience (slow and tidy).
This is a global setting which also affects the
.Cm blame
view.
.El
.Pp
The options for
.Cm tog diff
are as follows:
.Bl -tag -width Ds
.It Fl a
Treat file contents as ASCII text even if binary data is detected.
.It Fl C Ar number
Set the number of context lines shown in the diff.
By default, 3 lines of context are shown.
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
If this directory is a
.Xr got 1
work tree, use the repository path associated with this work tree.
.It Fl w
Ignore whitespace-only changes.
.El
.It Cm blame Oo Fl c Ar commit Oc Oo Fl r Ar repository-path Oc Ar path
Display line-by-line history of a file at the specified path.
.Pp
The key bindings for
.Cm tog blame
are as follows (N denotes optional prefixed count modifier):
.Bl -tag -width Ds
.It Cm Down-arrow, j, Ctrl-n
Move the selection cursor down N pages (default: 1).
.It Cm Up-arrow, k, Ctrl-p
Move the selection cursor up N pages (default: 1).
.It Cm Right-arrow, l
Scroll view to the right N increments (default: 1).
.br
File output moves left on the screen.
.It Cm Left-arrow, h
Scroll view to the left N increments (default: 1).
.br
File output moves right on the screen.
.It Cm $
Scroll view to the rightmost position.
.It Cm 0
Scroll view left to the start of the line.
.It Cm Page-down, Space, Ctrl+f, f
Move the selection cursor down N pages (default: 1).
.It Cm Page-up, Ctrl+b, b
Move the selection cursor up N pages (default: 1).
.It Cm Ctrl+d, d
Move the selection cursor down N half pages (default: 1).
.It Cm Ctrl+u, u
Move the selection cursor up N half pages (default: 1).
.It Cm Home, g
Move the selection cursor to the first line of the file.
.It Cm End, G
Move the selection cursor to the last line of the file.
.It Cm Enter
Open a
.Cm diff
view for the currently selected line's commit.
.It Cm c
Reload the
.Cm blame
view with the version of the file as found in the currently
selected line's commit.
.It Cm p
Reload the
.Cm blame
view with the version of the file as found in the parent commit of the
currently selected line's commit.
.It Cm C
Reload the
.Cm blame
view with the previously blamed commit.
.It Cm /
Prompt for a search pattern and start searching for matching lines.
The search pattern is an extended regular expression.
Regular expression syntax is documented in
.Xr re_format 7 .
.It Cm n
Find the Nth next line which matches the current search pattern (default: 1).
.It Cm N
Find the Nth previous line which matches the current search pattern
(default: 1).
.It Cm A
Change the diff algorithm.
Supported diff algorithms are Myers (quick and dirty) and
Patience (slow and tidy).
This is a global setting which also affects the
.Cm diff
view.
.El
.Pp
The options for
.Cm tog blame
are as follows:
.Bl -tag -width Ds
.It Fl c Ar commit
Start traversing history at the specified
.Ar commit .
The expected argument is the name of a branch or a commit ID SHA1 hash.
An abbreviated hash argument will be expanded to a full SHA1 hash
automatically, provided the abbreviation is unique.
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
If this directory is a
.Xr got 1
work tree, use the repository path associated with this work tree.
.El
.It Cm tree Oo Fl c Ar commit Oc Oo Fl r Ar repository-path Oc Op Ar path
Display the repository tree.
If a
.Ar path
is specified, show tree entries at this path.
.Pp
Displayed tree entries may carry one of the following trailing annotations:
.Bl -column YXZ description
.It @ Ta entry is a symbolic link
.It / Ta entry is a directory
.It * Ta entry is an executable file
.It $ Ta entry is a Git submodule
.El
.Pp
Symbolic link entries are also annotated with the target path of the link.
.Pp
The key bindings for
.Cm tog tree
are as follows (N denotes optional prefixed count modifier):
.Bl -tag -width Ds
.It Cm Down-arrow, j, Ctrl-n
Move the selection cursor down N lines (default: 1).
.It Cm Up-arrow, k, Ctrl-p
Move the selection cursor up N lines (default: 1).
.It Cm Page-down, Space, Ctrl+f, f
Move the selection cursor down N pages (default: 1).
.It Cm Page-up, Ctrl+b, b
Move the selection cursor up N pages (default: 1).
.It Cm Ctrl+d, d
Move the selection cursor down N half pages (default: 1).
.It Cm Ctrl+u, u
Move the selection cursor up N half pages (default: 1).
.It Cm Home, g
Move the selection cursor to the first entry.
.It Cm End, G
Move the selection cursor to the last entry.
.It Cm Enter
Enter the currently selected directory, or switch to the
.Cm blame
view for the currently selected file.
.It Cm l
Open a
.Cm log
view for the currently selected tree entry.
.It Cm r
Open a
.Cm ref
view listing all references in the repository.
This can then be used to open a new
.Cm tree
view for arbitrary branches and tags.
.It Cm Backspace
Move back to the Nth parent directory (default: 1).
.It Cm i
Show object IDs for all objects displayed in the
.Cm tree
view.
.It Cm /
Prompt for a search pattern and start searching for matching tree entries.
The search pattern is an extended regular expression which is matched
against the tree entry's name.
Regular expression syntax is documented in
.Xr re_format 7 .
.It Cm n
Find the Nth next tree entry which matches the current search pattern
(default: 1).
.It Cm N
Find the Nth previous tree entry which matches the current search pattern
(default: 1).
.El
.Pp
The options for
.Cm tog tree
are as follows:
.Bl -tag -width Ds
.It Fl c Ar commit
Start traversing history at the specified
.Ar commit .
The expected argument is the name of a branch or a commit ID SHA1 hash.
An abbreviated hash argument will be expanded to a full SHA1 hash
automatically, provided the abbreviation is unique.
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
If this directory is a
.Xr got 1
work tree, use the repository path associated with this work tree.
.El
.It Cm ref Oo Fl r Ar repository-path Oc
Display references in the repository.
.Pp
The key bindings for
.Cm tog ref
are as follows (N denotes optional prefixed count modifier):
.Bl -tag -width Ds
.It Cm Down-arrow, j, Ctrl-n
Move the selection cursor down N lines (default: 1).
.It Cm Up-arrow, k, Ctrl-p
Move the selection cursor up N lines (default: 1).
.It Cm Page-down, Space, Ctrl+f, f
Move the selection cursor down N pages (default: 1).
.It Cm Page-up, Ctrl+b, b
Move the selection cursor up N pages (default: 1).
.It Cm Ctrl+d, d
Move the selection cursor down N half pages (default: 1).
.It Cm Ctrl+u, u
Move the selection cursor up N half pages (default: 1).
.It Cm Home, g
Move the selection cursor to the first reference.
.It Cm End, G
Move the selection cursor to the last reference.
.It Cm Enter
Open a
.Cm log
view which begins traversing history at the commit resolved via the
currently selected reference.
.It Cm t
Open a
.Cm tree
view showing the tree resolved via the currently selected reference.
.It Cm i
Show object IDs for all non-symbolic references displayed in the
.Cm ref
view.
.It Cm m
Show last modified date of each displayed reference.
.It Cm o
Toggle display order of references between sort by name and sort by timestamp.
.It Cm /
Prompt for a search pattern and start searching for matching references.
The search pattern is an extended regular expression which is matched
against absolute reference names.
Regular expression syntax is documented in
.Xr re_format 7 .
.It Cm n
Find the Nth next reference which matches the current search pattern
(default: 1).
.It Cm N
Find the Nth previous reference which matches the current search pattern
(default: 1).
.It Cm Ctrl+l
Reload the list of references displayed by the
.Cm ref
view.
.El
.Pp
The options for
.Cm tog ref
are as follows:
.Bl -tag -width Ds
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
If this directory is a
.Xr got 1
work tree, use the repository path associated with this work tree.
.El
.El
.Sh ENVIRONMENT
.Bl -tag -width TOG_VIEW_SPLIT_MODE
.It Ev TOG_DIFF_ALGORITHM
Determines the default diff algorithm used by
.Nm .
Supported diff algorithms are Myers (quick and dirty) and
Patience (slow and tidy).
Valid values for
.Ev TOG_DIFF_ALGORITHM
are
.Dq patience
and
.Dq myers .
If unset, the Myers diff algorithm will be used by default.
.It Ev TOG_VIEW_SPLIT_MODE
Determines the default layout of split-screen views.
If set to
.Dq h
or
.Dq H ,
.Nm
will use horizontal split by default.
Otherwise, vertical split will be used.
The
.Cm S
key can be used to switch between vertical and horizontal split layout
at run-time.
.It Ev TOG_COLORS
.Nm
shows colorized output if this variable is set to a non-empty value.
The default color scheme can be modified by setting the environment
variables documented below.
The colors available in color schemes are
.Dq black ,
.Dq red ,
.Dq green ,
.Dq yellow ,
.Dq blue ,
.Dq magenta ,
.Dq cyan ,
and
.Dq default
which maps to the terminal's default foreground color.
.It Ev TOG_COLOR_DIFF_MINUS
The color used to mark up removed lines in diffs.
If not set, the default value
.Dq magenta
is used.
.It Ev TOG_COLOR_DIFF_PLUS
The color used to mark up added lines in diffs.
If not set, the default value
.Dq cyan
is used.
.It Ev TOG_COLOR_DIFF_CHUNK_HEADER
The color used to mark up chunk header lines in diffs.
If not set, the default value
.Dq yellow
is used.
.It Ev TOG_COLOR_DIFF_META
The color used to mark up meta data in diffs.
If not set, the default value
.Dq green
is used.
.It Ev TOG_COLOR_TREE_SUBMODULE
The color used to mark up submodule tree entries.
If not set, the default value
.Dq magenta
is used.
.It Ev TOG_COLOR_TREE_SYMLINK
The color used to mark up symbolic link tree entries.
If not set, the default value
.Dq magenta
is used.
.It Ev TOG_COLOR_TREE_DIRECTORY
The color used to mark up directory tree entries.
If not set, the default value
.Dq cyan
is used.
.It Ev TOG_COLOR_TREE_EXECUTABLE
The color used to mark up executable file tree entries.
If not set, the default value
.Dq green
is used.
.It Ev TOG_COLOR_COMMIT
The color used to mark up commit IDs.
If not set, the default value
.Dq green
is used.
.It Ev TOG_COLOR_AUTHOR
The color used to mark up author information.
If not set, the default value
.Dq cyan
is used.
.It Ev TOG_COLOR_DATE
The color used to mark up date information.
If not set, the default value
.Dq yellow
is used.
.It Ev TOG_COLOR_REFS_HEADS
The color used to mark up references in the
.Dq refs/heads/
namespace.
If not set, the default value
.Dq green
is used.
.It Ev TOG_COLOR_REFS_TAGS
The color used to mark up references in the
.Dq refs/tags/
namespace.
If not set, the default value
.Dq magenta
is used.
.It Ev TOG_COLOR_REFS_REMOTES
The color used to mark up references in the
.Dq refs/remotes/
namespace.
If not set, the default value
.Dq yellow
is used.
.It Ev TOG_COLOR_REFS_BACKUP
The color used to mark up references in the
.Dq refs/got/backup/
namespace.
If not set, the default value
.Dq cyan
is used.
.El
.Sh EXIT STATUS
.Ex -std tog
.Sh SEE ALSO
.Xr got 1 ,
.Xr git-repository 5 ,
.Xr re_format 7
.Sh AUTHORS
.An Christian Weisgerber Aq Mt naddy@openbsd.org
.An Josh Rickmar Aq Mt jrick@zettaport.com
.An Joshua Stein Aq Mt jcs@openbsd.org
.An Mark Jamsek Aq Mt mark@jamsek.dev
.An Martin Pieuchot Aq Mt mpi@openbsd.org
.An Omar Polo Aq Mt op@openbsd.org
.An Stefan Sperling Aq Mt stsp@openbsd.org
.An Klemens Nanni Aq Mt kn@openbsd.org
