.\"
.\" Copyright (c) 2018 Stefan Sperling
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt TOG 1
.Os
.Sh NAME
.Nm tog
.Nd git repository browser
.Sh SYNOPSIS
.Nm
.Ar command
.Op Fl h
.Op Ar arg ...
.Sh DESCRIPTION
.Nm
is an interactive read-only browser for git repositories.
This repository format is described in
.Xr git-repository 5 .
.Pp
.Nm
supports several types of views which display repository data.
An arbitrary number of views may be opened simultaneously by
navigating the repository with
.Nm .
Sometimes, if one view is opened from another view, the child view
is linked to its parent view and both views will keep their data
display in sync.
The supported views are:
.Bl -tag -width Ds
.It Cm log view
Displays commits in the repository's history.
This view is displayed initially if no
.Ar command
is specified.
.It Cm diff view
Displays changes made in a particular commit.
.It Cm blame view
Displays the line-by-line history of a file.
.It Cm tree view
Displays the tree corresponding to a particular commit.
.El
.Pp
.Nm
provides global and command-specific key bindings and options.
The global key bindings are:
.Bl -tag -width Ds
.It Cm Q
Quit
.Nm .
.It Cm q
Quit the view which is in focus.
.It Cm Tab
Switch focus to the next view.
Cycles through all open views.
.It Cm ~
Switch focus to the previous view.
Cycles through all open views.
.El
.Pp
Global options must precede the command name, and are as follows:
.Bl -tag -width tenletters
.It Fl h
Display usage information.
.El
.Pp
The commands for
.Nm
are as follows:
.Bl -tag -width blame
.It Cm log [ Fl c Ar commit ] [ Fl r Ar repository-path ] [ path ]
Display history of a repository.
If a
.Ar path
is specified, show only commits which modified this path.
.Pp
This command is also executed if no explicit command is specified.
.Pp
The key bindings for
.Cm tog log
are as follows:
.Bl -tag -width Ds
.It Cm Down-arrow, j, ], Page-down
Move the selection cursor down.
.It Cm Up-arrow, k, [, Page-up
Move the selection cursor up.
.It Cm Enter
Switch to the
.Cm diff
view showing file changes made in the currently selected commit.
The diff view is linked to the log view so either view will be
updated when the other switches to a different commit.
.It Cm t
Switch to the
.Cm tree
view showing the tree for the currently selected commit.
.El
.Pp
The options for
.Cm tog log
are as follows:
.Bl -tag -width Ds
.It Fl c Ar commit
Start traversing history at the specified
.Ar commit .
The expected argument is the name of a branch or a SHA1 hash which corresponds
to a commit object.
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
.El
.It Cm diff [ Ar repository-path ] Ar object1 Ar object2
Display the differences between two objects in the repository.
Each
.Ar object
argument is a SHA1 hash which corresponds to the object.
Both objects must be of the same type (blobs, trees, or commits).
If the
.Ar repository path
is omitted, use the current working directory.
.Pp
The key bindings for
.Cm tog diff
are as follows:
.Bl -tag -width Ds
.It Cm Down-arrow, j, Page-down, Space
Scroll down.
.It Cm Up-arrow, k, Page-up
Scroll up.
.It [
Switch to the previous commit in parent
.Cm log view .
.It ]
Switch to the next commit in parent
.Cm log view .
.El
.It Cm blame [ Fl c Ar commit ] [ Fl r Ar repository-path ] Ar path
Display line-by-line history of a file at the specified path.
.Pp
The key bindings for
.Cm tog blame
are as follows:
.Bl -tag -width Ds
.It Cm Down-arrow, j, Page-down, Space
Move the selection cursor down.
.It Cm Up-arrow, k, Page-up
Move the selection cursor up.
.It Cm Enter
Switch to the
.Cm diff
view for the currently selected line's commit.
.It Cm b
Show the
.Cm blame
view for the version of the file in the currently selected line's commit.
.It Cm p
Show the
.Cm blame
view for the version of the file in the currently selected line's commit's
parent commit.
.It Cm B
Switch the
.Cm blame
view back to the previously blamed commit.
.El
.Pp
The options for
.Cm tog blame
are as follows:
.Bl -tag -width Ds
.It Fl c Ar commit
Start traversing history at the specified
.Ar commit .
The expected argument is the name of a branch or a SHA1 hash which corresponds
to a commit object.
.It Fl r Ar repository-path
Use the repository at the specified path.
If not specified, assume the repository is located at or above the current
working directory.
.El
.It Cm tree [ Fl c Ar commit ] [ Ar repository-path ]
Display the repository tree.
If the
.Ar repository path
is omitted, assume the repository is located in the current working directory.
.Pp
The key bindings for
.Cm tog tree
are as follows:
.Bl -tag -width Ds
.It Cm Down-arrow, j, Page-down
Move the selection cursor down.
.It Cm Up-arrow, k, Page-up
Move the selection cursor up.
.It Cm Enter
Enter the currently selected directory, or switch to the
.Cm blame
view for the currently selected file.
.It Cm l
Switch to the
.Cm log
view for the currently selected tree entry.
.It Cm Left-arrow
Move back to the parent directory.
.It Cm i
Show the object IDs for all objects displayed in the
.Cm tree
view.
.El
.Pp
The options for
.Cm tog tree
are as follows:
.Bl -tag -width Ds
.It Fl c Ar commit
Start traversing history at the specified
.Ar commit .
The expected argument is the name of a branch or a SHA1 hash which corresponds
to a commit object.
.El
.El
.Sh EXIT STATUS
.Ex -std tog
.Sh SEE ALSO
.Xr git-repository 5
.Sh AUTHORS
.An Stefan Sperling Aq Mt stsp@openbsd.org
