REGRESS_TARGETS=checkout update status log add rm diff
NOOBJ=Yes

checkout:
	./checkout.sh

update:
	./update.sh

status:
	./status.sh

log:
	./log.sh

add:
	./add.sh

rm:
	./rm.sh

diff:
	./diff.sh

.include <bsd.regress.mk>
