REGRESS_TARGETS=checkout update status log add rm diff blame commit \
	cherrypick backout rebase import histedit
NOOBJ=Yes

checkout:
	./checkout.sh

update:
	./update.sh

status:
	./status.sh

log:
	./log.sh

add:
	./add.sh

rm:
	./rm.sh

diff:
	./diff.sh

blame:
	./blame.sh

commit:
	./commit.sh

cherrypick:
	./cherrypick.sh

backout:
	./backout.sh

rebase:
	./rebase.sh

import:
	./import.sh

histedit:
	./histedit.sh

.include <bsd.regress.mk>
