REGRESS_TARGETS=checkout update status log add rm diff commit \
	cherrypick backout rebase
NOOBJ=Yes

checkout:
	./checkout.sh

update:
	./update.sh

status:
	./status.sh

log:
	./log.sh

add:
	./add.sh

rm:
	./rm.sh

diff:
	./diff.sh

commit:
	./commit.sh

cherrypick:
	./cherrypick.sh

backout:
	./backout.sh

rebase:
	./rebase.sh

.include <bsd.regress.mk>
