SUBDIR = got-read-blob got-read-commit got-read-object got-read-tree \
	got-read-tag got-fetch-pack got-index-pack got-read-pack \
	got-read-gitconfig got-read-gotconfig got-send-pack \
	got-read-patch got-http

.include <bsd.subdir.mk>
