.\"
.\" Copyright (c) 2024 Omar Polo <op@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOTD-SECRETS.CONF 5
.Os
.Sh NAME
.Nm gotd-secrets.conf
.Nd gotd secrets file
.Sh DESCRIPTION
.Nm
holds the authentication data and HMAC secrets for
.Xr gotd 8
notifications.
This file must be owned by the root user and must not be readable
by any other users.
.Pp
The file format is line-based, with one entry per line.
Comments can be put at the start of the line using a hash mark
.Pq Sq # ,
and extend to the end of it.
Blank lines are also ignored.
.Pp
The entries have the following syntax:
.Pp
.Dl type key value
.Pp
with spaces or tabs to separate the fields.
No quoting is supported, so a space or a tab can't appear as part of
any field.
.Pp
The type is one of:
.Bl -tag -width Ds
.It Ic auth
The entry is for HTTP Basic Authentication.
.Ar key
is the username and
.ar value
the password.
The username is also used to identify this secret.
.It Ic hmac
The entry is for signing the notification HTTP payload with HMAC.
The
.Ar key
is a label to identify this secret and
.Ar value
is the HMAC secret.
.Pp
Suitable secrets can be generated with
.Xr openssl 1
as follows:
.Pp
.Dl $ openssl rand -base64 32
.El
.Pp
The key must be unique between entries with the same type.
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa /etc/gotd-secrets.conf
Location of the
.Nm
configuration file.
.El
.Sh EXAMPLES
This example configuration defines two secrets, the first for
HTTP authentication and the second for HMAC signing.
.Bd -literal -offset indent
# /etc/gotd-secrets.conf
auth flan super-strong-password!
hmac hacker q0tcl8QhjYs7U75MW/2rwB30CpdbAhONkfLGxFHm/+8=
.Ed
.Pp
These values can be referenced in
.Xr gotd.conf 5
as:
.Bd -literal -offset indent
# /etc/gotd.conf
repository "openbsd/ports" {
	path "/var/git/ports.git"
	permit rw :porters
	permit ro anonymous

	notify {
		url https://flan.com/notify/ auth flan
		url https://hacker.com/notify/ hmac hacker
	}
}
.El
.Sh SEE ALSO
.Xr got 1 ,
.Xr gotsh 1 ,
.Xr gotd.conf 5 ,
.Xr gotd 8
