.\"
.\" Copyright (c) 2024 Omar Polo <op@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOTD-SECRETS.CONF 5
.Os
.Sh NAME
.Nm gotd-secrets.conf
.Nd gotd secrets file
.Sh DESCRIPTION
.Nm
holds the authentication data and HMAC secrets for
.Xr gotd 8
notifications.
This file must be owned by the root user and must not be readable
by any other users.
.Pp
The file format is line-based, with one entry per line.
Comments can be put at the start of the line using a hash mark
.Pq Sq # ,
and extend to the end of it.
Empty lines are also ignored.
.Pp
Each entry is made by blanks-separated words.
Arguments containing whitespaces should be surrounded by single or double
quotes.
.Pp
The supported entries are:
.Bl -tag -width Ds
.It Ic auth Ar label Ic user Ar user Ic password Ar password
The entry is for HTTP Basic Authentication.
.It Ic hmac Ar label Ar secret
The entry is for signing the notification HTTP payload with HMAC.
A suitable
.Ar secret
can be generated with
.Xr openssl 1
as follows:
.Pp
.Dl $ openssl rand -base64 32
.El
.Pp
The
.Ar label
must be unique between entries with the same type
.Pq i.e. Ic auth No or Ic hmac .
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa /etc/gotd-secrets.conf
Location of the
.Nm
configuration file.
.El
.Sh EXAMPLES
This example configuration defines two secrets, the first for
HTTP authentication and the second for HMAC signing.
.Bd -literal -offset indent
# /etc/gotd-secrets.conf
auth mochi user "flan" password "super-strong-password!"
hmac hacker q0tcl8QhjYs7U75MW/2rwB30CpdbAhONkfLGxFHm/+8=
.Ed
.Pp
These values can be referenced in
.Xr gotd.conf 5
as:
.Bd -literal -offset indent
# /etc/gotd.conf
repository "openbsd/src" {
	path "/var/git/src.git"
	permit rw :hackers

	notify {
		url https://flan.com/ci/ auth mochi hmac hacker
	}
}
.El
.Sh SEE ALSO
.Xr got 1 ,
.Xr gotsh 1 ,
.Xr gotd.conf 5 ,
.Xr gotd 8
